# Generated by Django 4.2.4 on 2023-08-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
