# Generated by Django 4.2.4 on 2023-08-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_customusermodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='products_purchased',
            field=models.ManyToManyField(blank=True, to='home.product'),
        ),
    ]
