# Generated by Django 4.2.4 on 2023-08-06 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_product_product_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 7, 0, 47, 38, 432839), null=True),
        ),
    ]
